package gsync

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// SharedReason classifies how an entry was identified as shared.
type SharedReason int

const (
	// SharedManual means the entry came from
	// state.modules.gdrive_sync.shared_excludes (operator-curated for
	// owned-but-shared-out folders that have no filesystem signal).
	SharedManual SharedReason = iota
)

// String returns a stable two-letter token for the source column of
// `dot gsync shared list` output.
func (r SharedReason) String() string {
	switch r {
	case SharedManual:
		return "manual"
	default:
		return "?"
	}
}

// SharedEntry is one row returned by ScanShared.
type SharedEntry struct {
	RelPath string
	Reason  SharedReason
	Detail  string // human-readable detail (e.g. realpath suffix); "" for plain manual
}

// sharedDrivesBasename is the top-level directory the Drive Desktop
// client mounts shared drives under, parallel to "My Drive".
const sharedDrivesBasename = "Shared drives"

// IsSharedDriveMount reports whether mirrorPath itself resolves under
// a Drive Desktop "Shared drives" root. Pull/Push refuse to run in
// that case — the workspace-authoritative semantics make no sense for
// content the user does not own.
func IsSharedDriveMount(mirrorPath string) bool {
	target, err := filepath.EvalSymlinks(strings.TrimRight(mirrorPath, "/"))
	if err != nil {
		return false
	}
	return pathHasComponent(target, sharedDrivesBasename)
}

// ScanShared returns the operator's manual shared-excludes list. Each manual
// entry is reported even if it is missing on disk so the user can prune via
// `shared remove`. Output is sorted by RelPath.
func ScanShared(root string, manual []string) ([]SharedEntry, error) {
	root = strings.TrimRight(root, "/")
	if root == "" {
		return nil, nil
	}

	entries := make(map[string]SharedEntry)

	for _, rel := range manual {
		rel = strings.TrimSpace(rel)
		if rel == "" {
			continue
		}
		entry := SharedEntry{RelPath: rel, Reason: SharedManual}
		full := filepath.Join(root, rel)
		if _, err := os.Lstat(full); err != nil {
			entry.Detail = "(missing)"
		}
		entries[rel] = entry // overrides any auto match — operator intent wins
	}

	out := make([]SharedEntry, 0, len(entries))
	for _, e := range entries {
		out = append(out, e)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].RelPath < out[j].RelPath })
	return out, nil
}

// pathHasComponent returns true if any path component of p (split by
// the OS separator) equals name.
func pathHasComponent(p, name string) bool {
	for _, part := range strings.Split(p, string(filepath.Separator)) {
		if part == name {
			return true
		}
	}
	return false
}

// MaterializeRuntimeExcludesFile writes the merged dynamic exclude list to a
// per-run file under configDir. Shared entries protect Drive/shared-folder
// boundaries; gitTracked entries keep Git-owned files out of rsync passes.
func MaterializeRuntimeExcludesFile(configDir string, entries []SharedEntry, gitTracked []string) (string, error) {
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return "", fmt.Errorf("creating config dir %q: %w", configDir, err)
	}
	path := filepath.Join(configDir, localSharedDynName)

	var b strings.Builder
	b.WriteString("# Auto-generated by `dot gsync` — do not edit.\n")
	b.WriteString("# Runtime excludes: shared folders + Git-tracked relpaths.\n")
	for _, e := range entries {
		// rsync exclude syntax: `/path` matches at the source root.
		// Trailing slash makes it match a directory specifically.
		fmt.Fprintf(&b, "/%s\n", strings.TrimSuffix(e.RelPath, "/"))
		fmt.Fprintf(&b, "/%s/\n", strings.TrimSuffix(e.RelPath, "/"))
	}
	for _, rel := range gitTracked {
		rel = normalizeRel(rel)
		if rel == "" {
			continue
		}
		fmt.Fprintf(&b, "/%s\n", rel)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0644); err != nil {
		return "", fmt.Errorf("writing shared excludes %q: %w", path, err)
	}
	return path, nil
}
