package syncer

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// gitSubmodulePaths returns the submodule paths declared in
// <root>/.gitmodules, sorted. Submodules are never synced by `dot sync` —
// they sync through Git itself — so these paths become a dynamic exclude
// layer that follows submodule additions/removals automatically.
// Missing .gitmodules or a parse failure returns nil (non-Git workspaces
// stay usable).
func gitSubmodulePaths(root string) []string {
	root = strings.TrimRight(root, "/")
	gitmodules := filepath.Join(root, ".gitmodules")
	if _, err := os.Stat(gitmodules); err != nil {
		return nil
	}
	out, err := exec.Command("git", "config", "-f", gitmodules, "--get-regexp", `submodule\..*\.path`).Output()
	if err != nil {
		return nil
	}
	seen := map[string]bool{}
	var paths []string
	for _, line := range strings.Split(string(out), "\n") {
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		rel := normalizeRel(strings.Join(fields[1:], " "))
		if rel == "" || seen[rel] {
			continue
		}
		seen[rel] = true
		paths = append(paths, rel)
	}
	sort.Strings(paths)
	return paths
}

// gitTrackedForSync returns the root repo's tracked relpaths, excluding
// gitlink (submodule) entries. Unlike gitTrackedRelPaths it deliberately
// does NOT recurse into submodules: submodule content is out of scope for
// the sync set. Best-effort — errors return an empty set.
func gitTrackedForSync(root string) map[string]bool {
	root = strings.TrimRight(root, "/")
	out, err := exec.Command("git", "-C", root, "ls-files", "-z", "-s").Output()
	if err != nil {
		return map[string]bool{}
	}
	paths := map[string]bool{}
	for _, raw := range bytes.Split(out, []byte{0}) {
		entry := string(raw)
		if entry == "" {
			continue
		}
		// Format: "<mode> <object> <stage>\t<path>"
		tab := strings.IndexByte(entry, '\t')
		if tab < 0 {
			continue
		}
		meta := entry[:tab]
		rel := normalizeRel(entry[tab+1:])
		if rel == "" {
			continue
		}
		if strings.HasPrefix(meta, "160000 ") {
			continue // gitlink — submodule pointer, not a file
		}
		paths[filepath.ToSlash(rel)] = true
	}
	return paths
}

// unionTrackedWithBaseline returns the sorted union of currently tracked
// relpaths and baseline manifest keys.
//
// The baseline half is what makes deletes propagate: a tracked file removed
// locally drops out of `git ls-files`, and without its baseline entry the
// mirror copy would fall through to the final `--exclude=*` — rsync protects
// excluded destination files from --delete, so the stale copy would live
// forever. Keeping baseline keys in the include list lets --delete-after
// remove it; the entry ages out at the next baseline refresh.
func unionTrackedWithBaseline(tracked map[string]bool, baseline map[string]Fingerprint) []string {
	seen := make(map[string]bool, len(tracked)+len(baseline))
	for rel := range tracked {
		seen[rel] = true
	}
	for rel := range baseline {
		seen[rel] = true
	}
	out := make([]string, 0, len(seen))
	for rel := range seen {
		out = append(out, rel)
	}
	sort.Strings(out)
	return out
}

// MaterializeSubmodulesDynFile writes the submodule exclude layer to
// <dir>/submodules.dyn.conf. Always written (even empty) for predictable
// layering. Returns the file path.
//
// dir is the store directory for a real run and a temp directory for a
// preview: the file is a per-run artifact rsync needs on disk, so a preview
// still writes it, just not into the tree it is previewing.
func MaterializeSubmodulesDynFile(dir string, submodules []string) (string, error) {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("creating store dir: %w", err)
	}
	out := filepath.Join(dir, localSubmodulesDynName)
	var b strings.Builder
	b.WriteString("# Auto-generated by `dot sync` — do not edit.\n")
	b.WriteString("# Git submodules are excluded from sync: they sync through Git.\n")
	for _, rel := range submodules {
		fmt.Fprintf(&b, "/%s\n", rel)
		fmt.Fprintf(&b, "/%s/\n", rel)
	}
	if err := os.WriteFile(out, []byte(b.String()), 0644); err != nil {
		return "", fmt.Errorf("writing %s: %w", out, err)
	}
	return out, nil
}

// MaterializeTrackedIncludesFile writes the tracked-union include layer to
// <dir>/tracked-includes.dyn.conf (one anchored relpath per line, rsync
// include-from syntax). Returns the file path. dir carries the same
// real-run/preview split as MaterializeSubmodulesDynFile.
func MaterializeTrackedIncludesFile(dir string, rels []string) (string, error) {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("creating store dir: %w", err)
	}
	out := filepath.Join(dir, localTrackedDynName)
	var b strings.Builder
	b.WriteString("# Auto-generated by `dot sync` — do not edit.\n")
	b.WriteString("# Include layer: git-tracked relpaths ∪ baseline manifest keys.\n")
	for _, rel := range rels {
		rel = normalizeRel(rel)
		if rel == "" {
			continue
		}
		fmt.Fprintf(&b, "/%s\n", rel)
	}
	if err := os.WriteFile(out, []byte(b.String()), 0644); err != nil {
		return "", fmt.Errorf("writing %s: %w", out, err)
	}
	return out, nil
}

// submodulePathsForScan returns submodule paths regardless of the profile's
// exclude policy. prepareRuntimeFilters nils out the exclude list for peer
// profiles, but the tracked-include scan still needs to know where to look.
func submodulePathsForScan(root string) []string {
	return gitSubmodulePaths(root)
}

// gitTrackedInSubmodules collects tracked files inside each submodule, keyed by
// path relative to the outer workspace, recursing to any depth.
//
// `git ls-files` at the root reports a submodule as a single gitlink and never
// descends, so without this the include layer has no entry for anything inside
// one. That gap is invisible until a tracked file also matches an exclude
// pattern: rsync then skips it and the receiver reports a deletion.
//
// Depth matters here - dev/ carries submodules that carry their own. A
// fixed two-level walk would silently drop the third level and reintroduce
// exactly the bug this exists to prevent.
func gitTrackedInSubmodules(root string, subs []string) map[string]bool {
	out := map[string]bool{}
	collectTrackedInSubmodules(strings.TrimRight(root, "/"), "", subs, out, 0)
	return out
}

// maxSubmoduleDepth bounds the walk. Real trees are 2-3 deep; the limit only
// exists so a pathological or cyclic layout cannot spin forever.
const maxSubmoduleDepth = 8

func collectTrackedInSubmodules(absRoot, relPrefix string, subs []string, out map[string]bool, depth int) {
	if depth >= maxSubmoduleDepth {
		return
	}
	for _, sub := range subs {
		sub = strings.Trim(filepath.ToSlash(sub), "/")
		if sub == "" {
			continue
		}
		abs := filepath.Join(absRoot, sub)
		rel := sub
		if relPrefix != "" {
			rel = relPrefix + "/" + sub
		}
		for f := range gitTrackedForSync(abs) {
			out[rel+"/"+f] = true
		}
		collectTrackedInSubmodules(abs, rel, gitSubmodulePaths(abs), out, depth+1)
	}
}
